### ISSUE TITLE
Specification of response content when creating/updating a resource

### ISSUE THREAD

**Issue by christianz** [mikekelly/hal-rfc#11]
Hi,

I'm wondering why the RFC doesn't contain any information on what the response content should look like when POSTing or PUTting a resource. One API I'm working with says the created/updated resource should be linked to in the Location header (and the response be empty), while the API client I'm using says the created/updated resource should be part of the response from the POST/PUT. Which is correct?

**Comment by C06A** [comment]
> Which is correct?

As you mentioned this is up to the API. This spec defines the HAL **format** and not specific API.

Based on REST concept each HTTP request should return a resource, which in context of this spec should be in HAL format. So IMHO all requests (except potentially DELETE) should return HAL resource. Even error response may be a HAL resource... ;-)
