### ISSUE TITLE
rel + name combinations - should these be considered unique, or not?

### ISSUE THREAD

**Issue by kavika13** [mikekelly/hal-rfc#13]
> 5.5.  name
> 
>    The "name" property is OPTIONAL.
> 
>    Its value MAY be used as a secondary key for selecting Link Objects
>    which share the same relation type.

It isn't entirely clear in the spec whether `rel` + `name` should be unique, or whether duplication is allowed. I know that things that aren't explicitly disallowed are inherently allowed, but I think the lack of clarity here might lead to different interpretations by different libraries/consumers, and may cause APIs to build bugs into their interfaces.

I think some language should be added to the spec to make it very clear whether this is allowed or disallowed.

Maybe this is still undecided? If so, then it makes sense to me to allow combinations of `rel` + `name` to be duplicated:
1. `name` use is already optional, and you already have cases of multiple links when it isn't used
2. `hreflang`, `type`, and `profile` work better if duplication is allowed, for cases where content negotiation isn't used or can't be used, in particular for backwards compatibility

**Comment by merlynmg** [comment]
3. Derived media types and resource profiles are free to add their own uniqueness constraint, but wouldn't be able to remove that constraint if it were built into HAL
4. Clients and libraries could add `findOne` query variants to their API, similar to many existing DB query interfaces. This would allow clients to have more convenient access in cases where a derived media type or resource profile guaranteed the client a unique `rel` + `name` combination

**Comment by C06A** [comment]
Just like JSON relations can be duplicated. Nothing prevents duplications of rel + name combination.

The specific API using HAL may apply more constraints, but RFC should not enforce that IMHO.
