### ISSUE TITLE
HAL status?

### ISSUE THREAD

**Issue by DanielSchaffer** [mikekelly/hal-rfc#23]
According to https://tools.ietf.org/html/draft-kelly-json-hal-08, the most recent version of the draft expired in November 2016. Has HAL been abandoned?

**Comment by Neopallium** [comment]
HAL is being used by [OpenProject's API](http://docs.openproject.org/apiv3-doc/).

It would be interesting to link to other projects that are using it and libraries for encode/decode.

Here is a Go module for working with HAL APIs [go-json-hal](https://github.com/lectio/go-json-hal).

**Comment by C06A** [comment]
> HAL is being used by [OpenProject's API](http://docs.openproject.org/apiv3-doc/).
> 

The link is broken. Could somebody fix working link if it is exists?

**Comment by DanielSchaffer** [comment]
@C06A @Neopallium looks like a good link is https://docs.openproject.org/api/

**Comment by DracoBlue** [comment]
This PR updated at https://github.com/mikekelly/hal-rfc/pull/27 to -09 by @mikekelly!
