### ISSUE TITLE
Proposal for a JSON Schema to validate HAL

### ISSUE THREAD

**Issue by jenkin** [mikekelly/hal-rfc#28]
Ehi @mikekelly , glad to see this project is still alive! Just for curiosity, what led you to update the spec after seven (!) years of silence?

I'm going to use HAL for a side project but I need validation and want to use JSON Schema to document my profile. So I wrote the JSON Schema that formalize the latest version of HAL spec, if you are interested I can share it with you next week.

**Comment by jenkin** [comment]
Hi @mikekelly , here you can find the draft of a JSON Schema for HAL+JSON spec: https://jenkin.dev/json-schema-bricks/hal.schema.json. There is also a [dereferenced and minified version](https://jenkin.dev/json-schema-bricks/hal.schema.min.json).

In titles and descriptions you can find texts from spec v11.

```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/mikekelly/hal-rfc/master/hal.schema.json",
    "title": "JSON Hypertext Application Language",
    "description": "This document proposes a media type for representing resources and their relations with hyperlinks. Full specification at https://datatracker.ietf.org/doc/html/draft-kelly-json-hal. Its root object MUST be a Resource Object.",
    "allOf": [
        {
            "$ref": "#/$defs/Resource"
        }
    ],
    "$defs": { ... }
}
```

Properties of `_links` and `_embedded` objects are restricted to [Link Relations Types defined by IANA](https://www.iana.org/assignments/link-relations/link-relations.xhtml), with the addition of custom `curies` name for `_links`.

```
"propertyNames": {
    "anyOf": [
        {
            "$ref": "#/$defs/LinkRelationTypes"
        },
        {
            "type": "string",
            "const": "curies"
        }
    ]
}
```
Values of `hreflang` property of Link object are restricted to [Language Subtags defined by IANA](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).

```
"hreflang": {
    "title": "hreflang",
    "description": "Its value is a string and is intended for indicating the language of the target resource (as defined by [RFC5988](https://www.rfc-editor.org/info/rfc5988)).",
    "$ref": "https://jenkin.dev/json-schema-bricks/IANALanguageSubtags.schema.json"
}
```

Values of `type` property of Link object are restricted to [official Media Types defined by IANA](https://www.iana.org/assignments/media-types/media-types.xhtml), with the addition of `application/hal+json` mime type.

```
"type": {
    "title": "type",
    "description": "Its value is a string used as a hint to indicate the media type expected when dereferencing the target resource.",
    "oneOf": [
        {
            "title": "IANA Media Types",
            "description": "Official Media Types from IANA: https://www.iana.org/assignments/media-types/media-types.xhtml",
            "$ref": "https://jenkin.dev/json-schema-bricks/IANAMediaTypes.schema.json#/$defs/AllRegistries"
        },
        {
            "title": "HAL Media Type (not registered)",
            "type": "string",
            "const": "application/hal+json"
        }
    ]
},
```

Released under CC0 license, so do what you want with it. Best!

**Comment by mikekelly** [comment]
> Ehi @mikekelly , glad to see this project is still alive! Just for curiosity, what led you to update the spec after seven (!) years of silence?
>

It's been something I've been meaning to do for a while, and several folks had requested that I push this to RFC. I've been pretty busy over the last few years but I've decided to squeeze this in as it's so widely used it does probably deserve RFC status. The schema looks ok but is probably a bit strict in terms of enforcing only IANA registered relations. I'm closing this since this wont be included in the rfca
