### ISSUE TITLE
uniform metadata structure

### ISSUE THREAD

**Issue by BreiteSeite** [mikekelly/hal-rfc#8]
We currently have an internal debate on whatever format is better/correct. I'll post 2 examples (using the example from your website in a simplified form) to visualize our "dilemma":
## Version 1

``` javascript
{
    "_links": {
        "self": { "href": "/orders" },
        "next": { "href": "/orders?page=2" },
    },
}
```
## Version 2

``` javascript
{
    "_links": {
        "self": { "href": "/orders" },
        "next": { "href": "/orders?page=2" },
        "prev": null,
        "vnd:foo": null
    },
}
```

Version 2 is giving away ALL possible properties of the link (and embedded) object regardless if they contain a value or not.

Again, the example is extremely simplified. In this case, we only have pagination links and one other resource ("vnd:foo") which can exist but in this case doesn't.

Here are my thoughts:
### Version 1
- less "overhead" in response
- no way to figure out if the resource is just abstinent (not included and this request but could theoretically appear if it's reasonable for this specific resource) or can't be there per definition
### Version 2
- libraries can expect a fixed format and can throw exceptions if they are missing and delegate this to the user (of the library) to decide if this is correct behavior or not
- received response is similar to the documented response (because in the documentation you have to include all)
- :+1: would (probably) lead to better/cleaner client implementations, as hydration is based on keys, instead of values (for example [zfcampus/zf-hal (PHP)](https://github.com/zfcampus/zf-hal) hydrates based on values which is not optimal imho)
- probably a little bit confusing as per RFC (draft-07), embedded resources can be partial so it's not possible to expect an uniform response format in the first place (except the RFC would define that partial objects must have the same format for a given endpoint)
- :-1: embedded collections should be empty arrays, however this would open the possibility for them to be just null which would be bad in my opinion.

However, i feel i'm not _that_ confident to discuss whatever is the correct way of doing this, i was just giving away my initial thoughts on that.
# What this issue is about

I would like to here your opinion on which is the correct way and to **write it down in the RFC** because now the expected behavior is up to the (maintainer of the) libraries and i think this is not good as this will harm interoperability and causes headaches for the users.

Our backend library assumes Version 1 and skips empty values from the response and our frontend library expects Version 2 and is causing errors when accessing resources that aren't there and now we are unsure who is correct.

**Comment by mikekelly** [comment]
ok, sure. Please could you make a pull request with the appropriate additions

**Comment by BreiteSeite** [comment]
Hi @mikekelly 

First: Thank you for responding to this issue.

Second: I would like to hear your opinion on which variant you prefer? I prefer Variant 2. Do you too?

**Comment by ivan-gammel** [comment]
@BreiteSeite the problem with version 2 is that `null` value for some clients may cause a crash the same way as absence of the link does it - it's not safe either way, if some client is not handling the missing link correctly. The best way for any traversion client to handle this data model is to return optional object on link query, as shown in the example below:
```java 
Optional<Link> link = resource.link("rel:example");
if (link.isPresent()) { 
   if (link.get().isDeprecated()) { 
       LOG.warn("API rel:example is deprecated: client must be updated");
    }
   // do show the data or action link in UI
} else {
/** 
How this situation is handled depends on the context: absence of the link may be due to the user permissions (server-driven access control in UI), removal of the link after deprecation period etc. 
The implementation may write warning to the log, throw an exception or just do nothing.
*/
}
```

**Comment by C06A** [comment]
IMHO the spec is stating that either approach are fine and may be limited by the API designer. In some cases it may make sense to omit missing values and in other -- to use null. BTW this is what JSON supports. So it would be valid JSON serializer if it will omit null values and valid JSON parser would set null to the omitted attributes.

In my projects I am omitting values client doesn't need (your version 1). This also makes client less coupled to the server. Adding new elements on the server won't break the client, which will ignore them.

However there is one case when server provide pre-populated resource for client to review/modify and submit back. In this case server includes all nulls to inform the client that this fields exist and may be populated if needed. This is a basic concept I am follow to "inform" client of the complex structure expected in the response.

So my answer to your original question: IT DEPENDS

;-D
